FROM postgres

ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=database
ENV POSTGRES_PORT=5432

WORKDIR /iot

EXPOSE 5432

COPY /database/initdb.sql /docker-entrypoint-initdb.d/initdb.sql

ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD [ "postgres" ]