version: '3.8'

services:
  postgres:
    image: iot-postgres-image
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432"
    volumes:
      - ../database/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - network

  golang-server:
    image: iot-server-image
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - network


networks:
  network:
    driver: bridge